### ISSUE TITLE
Validator not working

### ISSUE THREAD

**Issue by visualcookie** [adonisjs/adonis-blog-demo#16]
Validations are not working and `validator.fails()` always returns `true` even tho every field has values and is unique. It's not even returning a `validator.message()` when some fields are not filled, but required.

Spec:
OS: Windows 10
NPM: 5.7.1
Node: 8.10.0

**Comment by RomainLanz** [comment]
Hey @visualcookie!

Could you try again please?

**Comment by visualcookie** [comment]
Don't know. Couldn't even build the assets now, got a new error:
`F:\__restructure\work\development\__tests\adonis-blog-demo\node_modules\process\browser.js: Cannot read property 'getAsset' of undefined`

**Comment by RomainLanz** [comment]
Could you delete the folder `.cache`, reinstall you deps and try again to run `adonis bundle`?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
