### ISSUE TITLE
Invalid CSS after "m": expected 1 selector or at-rule, was "module.exports = re"

### ISSUE THREAD

**Issue by HapLifeMan** [adonisjs/adonis-blog-demo#21]
Hey, I've got an error while running `npm run build:dev`...
It seems it comes from the `bootstrap` import, any idea? Thanks!

```
/Users/thomas/Sites/adonis-blog-demo/resources/assets/sass/app.scss: Invalid CSS after "m": expected 1 selector or at-rule, was "module.exports = re"
    at options.error (/Users/thomas/Sites/adonis-blog-demo/node_modules/node-sass/lib/index.js:291:26)
```

**Comment by RomainLanz** [comment]
Hey @HapLifeMan, @mmiscool! 👋 

I don't have any issue on my side, could you try to update your dependencies?

**Comment by fredure** [comment]
Bootstrap in boostrap.scss (node_modules/bootstrap/scss/) tries to mount the file in node_modules directory -  node-progress. How to avoid this?

**Comment by RomainLanz** [comment]
Hey guys !

I'll look into it when coming back from holiday!

**Comment by RomainLanz** [comment]
Related https://github.com/parcel-bundler/parcel/pull/1335

Waiting on the new release of Parcel that fix this bug.
