### ISSUE TITLE
TypeError: (intermediate value).handle is not a function

### ISSUE THREAD

**Issue by nyanen** [adonisjs/adonis-blog-demo#22]
```
TypeError: (intermediate value).handle is not a function
TypeError: (intermediate value).handle is not a function
    at ExceptionHandler.handle (C:\Users\user\blog\app\Exceptions\Handler.js:28:18)
    at Server._handleException (C:\Users\user\blog\node_modules\@adonisjs\framework\src\Server\index.js:254:21)
    at _executeServerMiddleware.then.then.catch (C:\Users\user\blog\node_modules\@adonisjs\framework\src\Server\index.js:441:14)
    at <anonymous>
```

I'm getting this error when loading `127.0.0.0:3333/` on Windows and Ubuntu with a fresh install of node 8.11.2 and adonisjs/cli@4.0.4.

Additionally, `127.0.0.0:3333/login` loads with a missing stylesheet and other resources.

**Comment by RomainLanz** [comment]
Hey @nyanen! 👋 

Have you followed all the step to install this application?

**Comment by nyanen** [comment]
Sorry it took me so long to get back. I had missed some steps, but now I'm stuck again. The `npm run build:dev` command never seems to finish building the css and js files it just gets stuck.

**Comment by RomainLanz** [comment]
Should be an issue with Parcel, waiting for the next release that is this week.

**Comment by nyanen** [comment]
Okay, thanks for the help.
