### ISSUE TITLE
Sorting posts & truncate 150

### ISSUE THREAD

**Issue by sequendnb** [adonisjs/adonis-blog-demo#9]
Hi all! Firstly sorry for my bad English please :) 

I offer to make some changes in **PostController.js** for:

From:
`const posts = await Post.all()`
> Post#1 (old)
> Post#2 (...)
> Post#3 (latest)

To:

`const posts = await Post.query().orderBy('id', 'desc').fetch()`

> Post#3 (latest)
> Post#2 (...)
> Post#1 (old)

**Comment by sequendnb** [comment]
Tell me please, how can i use in AdonisJS 4:
`{{ post.body | truncate (150) }}`

**| truncate (150)**  

When i type this, i see '**0**' but not 150 characters from **post.body**

Waiting for your reply! Thank you.

**Comment by sequendnb** [comment]
i found.. 
`{{ truncate(user.bio, 40, '...') }}`

i'm sorry.. i'm beginner

**Comment by thetutlage** [comment]
There is no concept of `filters` in Edge templates and hence `{{ post.body | truncate (150) }}` will never work.

So your last example is correct.

```js
{{ truncate(user.bio, 40, '...') }}
```
